wagtail/bakerydemo

- bakerydemo/blog/models.py
- bakerydemo/breads/models.py
- bakerydemo/templates/base.html
- bakerydemo/templates/blog/blog_index_page.html
- bakerydemo/templates/blog/blog_page.html
Adds a custom view via RoutablePageMixin to render blog posts related…to a particular tag via /[blog-index-slug]/tag/[tag-slug]
> View blog posts by tag

- readme.md
> Add documentation to discuss how to serve media on S3

- bakerydemo/locations/models.py
- bakerydemo/templates/locations/location_page.html
Closes #38 
@heymonkeyriot: After diving in, I realized a templatetag is a bit too heavy handed and not necessary to determine if a location is currently open.  
Instead, I added a model method.  Still useful, IMO.
> Logic to determine if a store is currently open

- contributing.md
Adds basic guidelines for contributing to this repo.
> adding contributing doc

- .gitignore
- readme.md
> Modify readme to cover virtualenv for manual setups

- bakerydemo/base/models.py
- bakerydemo/base/wagtail_hooks.py
- bakerydemo/breads/models.py
- Access to People, FooterText, BreadType and Country from custom menu items
- Now uses wagtail_hooks  rather than putting config in the models
- Resolves #22
> Refactor WagtailBakery admin menu item(s)

- bakerydemo/blog/models.py
@heymonkeyriot here is your helper method. Apologies for the oversight!
> Add helper method to get all BlogIndexPage's child BlogPage's tags

- bakerydemo/blog/models.py
- bakerydemo/static/css/main.css
- bakerydemo/templates/blog/blog_index_page.html
- bakerydemo/templates/blog/blog_page.html
> Use blog intro field on blog index, detail; blog bylines, avatars

- bakerydemo/blog/models.py
- bakerydemo/templates/blog/blog_index_page.html
- readme.md
- Also tweak indentation
- Stray readme addition
> Rename blogs method to get_posts; simplify list comprehensions

- bakerydemo/templates/blocks/blockquote.html
Minor PR. Looking at it, I think all of the block templates have some unnecessary HTML in them. Will raise an issue and other PR to deal with them.
> Blockquote tags

- bakerydemo/templates/blocks/intro_block.htm
c/f #85 I had thought the worst of myself and that I'd left lots of junk in html templates. Turns out I hadn't, which is nice, but there was a file we're not using, which is deleted in this PR.
> Remove unused template from templates/blocks

- bakerydemo/templates/blog/blog_page.html
- bakerydemo/templates/locations/location_page.html
> Remove todo comments that don't need doing

- bakerydemo/static/css/main.css
- bakerydemo/templates/base.html
- bakerydemo/templates/base/form_page.html
- bakerydemo/templates/includes/footer.html
- bakerydemo/templates/includes/header.html
- bakerydemo/templates/includes/messages.html
- bakerydemo/templates/tags/breadcrumbs.html
- bakerydemo/templates/tags/top_menu.html
- bakerydemo/templates/tags/top_menu_children.html
I've probably added fewer roles and labels than I should do, but I think this is at least an improvement and does mean that it's possible to keyboard tab navigate the site and improve the accessibility of it.
> Aria roles and labels across templates

- bakerydemo/templates/includes/footer.html
Closes #103
Not hugely imaginative. I think post-release we can wheel back to improving these but I think this work for version 1.
> Add links to footer and remove Facebook

- bakerydemo/locations/models.py
> Remove body from content_panels on LocationPage

- bakerydemo/templates/locations/locations_index_page.html
- Maps are already in location detail views - these lead readers out rather than in
> Remove map links from Locations index

- bakerydemo/locations/models.py
- bakerydemo/templates/base/home_page.html
- bakerydemo/templates/blocks/blockquote.html
- bakerydemo/templates/blocks/heading_block.html
- bakerydemo/templates/blog/blog_page.html
- bakerydemo/templates/breads/bread_page.html
- bakerydemo/templates/breads/breads_index_page.html
- bakerydemo/templates/includes/header.html
- Went through most files looking for linter and obvious errors
- Several big indentation change in templates
- Resolves #88
> PEP-8 and template cleanup

- bakerydemo/static/css/main.css
Hopefully a case of third time lucky. Sorry though. I promise I've tested this over and over to make sure I haven't done something stupid
c/f #135
> Fix li regression on homepage

- bakerydemo/blog/models.py
> Fix preview functionality on BlogIndex when route methods are present

- .travis.yml
- bakerydemo/settings/base.py
- requirements/base.txt
Fixes #144 
Pins requirements to the current latest version of Django and Wagtail.  Test drove the site post upgrade and everything seems functional.
> [144] Upgrade Django and Wagtail

- requirements/base.txt
Specify with a range rather than a fixed version, so that we don't have to do this on every point release...
> Upgrade to Wagtail 1.13

- bakerydemo/settings/base.py
- bakerydemo/urls.py
- requirements/base.txt
This is being dropped from Wagtail 2.0, and isn't used in this project.
> Remove API v1

- readme.md
Missing out an extra command for running.
> :pencil: extra docker command

- Vagrantfile
> Allow override of Vagrant settings

- bakerydemo/base/models.py
> Fix overlapping panels on Person name fields

- bakerydemo/locations/models.py
Fix **__str__** method of `OperatingHours`
> Fixes #214

- Dockerfile
Upgrade of the python version, depends on #235
> Update Python to 3.7 in Dockerfile

- bakerydemo/settings/production.py
- requirements/production.txt
> Update to boto3

- bakerydemo/base/fixtures/bakerydemo.json
Let's keep the bread as fresh as possible.
> Keep the year set to the current year

- requirements/production.txt
> Fix dependency conflict for issue

- Dockerfile
It's tiny, and pretty handy for debugging.
> include procps in RUN_DEPS

- requirements/production.txt
> Version bump psycopg2 and uwsgi to prevent segfault on heroku

- .gitignore
- vagrant/provision.sh
It's a next one part of [a story about an idempotent provisioning](https://github.com/wagtail/vagrant-wagtail-develop/pull/16) for a developers' env.
> An idempotent provisioning bakery

- bakerydemo/base/fixtures/bakerydemo.json
As per https://docs.wagtail.io/en/stable/releases/2.10.html#clean-name-field-added-to-form-builder-form-field-models
> populate FormField.clean_name in initial data

- bakerydemo/base/wagtail_hooks.py
- bakerydemo/settings/production.py
- fix some links that now redirect to a new location
- ensure all external links are https (not http)
> update external urls (https) & new links

- bakerydemo/base/fixtures/bakerydemo.json
This was previously creating a single `Page`, with multiple "specific" pages pointing to it.
> Fix initial page tree

- bakerydemo/base/wagtail_hooks.py
Having this in bakerydemo would be very useful to test this part of Wagtail, and it feels like a worthwhile feature to demo. I’ve added this to the `People` model in particular because it’s the most complex we have in bakerydemo.
> Add a demo of ModelAdmin InspectView on most complex model

- bakerydemo/settings/base.py
* Having this enabled in bakerydemo makes it easier to review some kinds of PRs
> add styleguide to bakerydemo

- bakerydemo/base/management/commands/create_random_data.py
It's very useful to have not just a small wagtail site to work with, but potentially large scales of data. This script can automatically create data, to allow for more extreme load / performance testing, both of components in the admin, main site utils and the main request/response cycle.
The foundations are here, interested in some more feedback on what else could be added.
This depends on #311 to work as expected.
> Add a util script to create large amounts of random data

- readme.md
I think we need the verb 'set up'.
> Fix spelling 'set up'

- bakerydemo/base/models.py
- bakerydemo/blog/models.py
- bakerydemo/breads/models.py
- bakerydemo/locations/models.py
- bakerydemo/templates/base.html
Just a few Wagtail 4.0 Upgrade considerations.
> Wagtail 4 considerations

- readme.md
The docker compose command has been updated from `docker-compose` to `docker compose` in the latest versions of Docker.
> update docker compose command

- readme.md
Fixes https://github.com/wagtail/bakerydemo/issues/391
> Small typo in code snippet in local setup section of readme instructions

- bakerydemo/settings/base.py
- requirements/base.txt
This is needed for `reset_demo` to work
> Install django-extensions

- bakerydemo/base/models.py
as per https://github.com/wagtail/wagtail/pull/10341#issuecomment-1512846879
> Add missing AutocompleteFields to Person model search_fields

- .env.example
- readme.md
Follow up on https://github.com/wagtail/bakerydemo/pull/426
> Add testing notes about CSP

- bakerydemo/templates/base.html
The fonts were removed in #431, but the references weren't removed
> Remove references to removed fonts

- bakerydemo/blog/models.py
- bakerydemo/recipes/models.py
It allows selecting multiple authors at once and functions as a great demo of this panel.
> Use MultipleChooserPanel instead of InlinePanel

- bakerydemo/templates/search/search_results.html
Updated bakerydemo/templates/search/search_results.html to handle external links.
> Add support for external links in search promotions.

- bakerydemo/base/wagtail_hooks.py
Available in v5.2 so this will work fine with current and future Wagtail
> Add list_export for Snippets

- bakerydemo/base/models.py
This PR is to validate the changes made in [#11818](https://github.com/wagtail/wagtail/pull/11818).
> Add icons to registered settings

- .gitpod.dockerfile
> Use workspace-python-3.12 image for gitpod

- Vagrantfile
- vagrant/provision.sh
This provides Python 3.10, which is the minimum supported version for Django 5.0
> Update Vagrant config to ubuntu/jammy64

- bakerydemo/static/css/main.css
- bakerydemo/templates/base.html
- bakerydemo/templates/includes/header.html
Following up to #493: Add a skip link to all the pages
> Add skip-link

- requirements/production.txt
- https://docs.djangoproject.com/en/stable/internals/deprecation/#deprecation-removed-in-5-1 https://github.com/wagtail/bakerydemo/blob/5e261b5b5defc2297ff37cdb9519e856950dc843/requirements/base.txt#L1
- Update boto3 to fix https://github.com/boto/boto3/issues/3766
- Remove explicit botocore dependency, as boto3 already depends on it
> Update boto3 and remove explicit botocore dependency
